# Dubai center coordinates
DUBAI_COORDINATES = {
    "center": [25.2048, 55.2708],  # Dubai's center
    "zoom": 11
}

# Neighborhood information with coordinates and quality-of-life metrics
NEIGHBORHOOD_INFO = {
    "Downtown Dubai": {
        "coordinates": [25.1972, 55.2744],
        "neighborhood": "Downtown Dubai",
        "commute_time": 15,
        "schools_rating": 4,
        "shopping_rating": 5,
        "dining_rating": 5,
        "parks_rating": 4,
        "metro_access": True,
        "beach_access": False,
        "lifestyle": "Singles/Couples",
        "parking_availability": "Adequate",
        "description": "Home to Burj Khalifa and Dubai Mall, Downtown Dubai is a bustling urban center with luxury apartments and a vibrant lifestyle. Excellent for dining, shopping, and entertainment, but among the most expensive areas to rent."
    },
    "Dubai Marina": {
        "coordinates": [25.0750, 55.1375],
        "neighborhood": "Dubai Marina",
        "commute_time": 25,
        "schools_rating": 3,
        "shopping_rating": 4,
        "dining_rating": 5,
        "parks_rating": 3,
        "metro_access": True,
        "beach_access": True,
        "lifestyle": "Mixed",
        "parking_availability": "Limited",
        "description": "A popular waterfront community with high-rise apartment buildings, a walkable marina promenade, and proximity to the beach. Popular among expats and offers a wide range of dining and nightlife options."
    },
    "JBR": {
        "coordinates": [25.0806, 55.1334],
        "neighborhood": "JBR",
        "commute_time": 30,
        "schools_rating": 3,
        "shopping_rating": 4,
        "dining_rating": 5,
        "parks_rating": 3,
        "metro_access": False,
        "beach_access": True,
        "lifestyle": "Mixed",
        "parking_availability": "Limited",
        "description": "Jumeirah Beach Residence is a beachfront community with apartment buildings, shops, and restaurants along The Walk. Known for its beachside living and vibrant atmosphere, but traffic can be congested."
    },
    "Business Bay": {
        "coordinates": [25.1860, 55.2826],
        "neighborhood": "Business Bay",
        "commute_time": 20,
        "schools_rating": 3,
        "shopping_rating": 4,
        "dining_rating": 4,
        "parks_rating": 3,
        "metro_access": True,
        "beach_access": False,
        "lifestyle": "Singles/Professionals",
        "parking_availability": "Adequate",
        "description": "A commercial and residential district near Downtown Dubai. Offers canal views and modern high-rise living with good access to business districts. More affordable than Downtown while still centrally located."
    },
    "Palm Jumeirah": {
        "coordinates": [25.1123, 55.1379],
        "neighborhood": "Palm Jumeirah",
        "commute_time": 35,
        "schools_rating": 4,
        "shopping_rating": 4,
        "dining_rating": 5,
        "parks_rating": 3,
        "metro_access": False,
        "beach_access": True,
        "lifestyle": "Luxury",
        "parking_availability": "Adequate",
        "description": "The iconic palm-shaped island featuring luxury villas, apartments, hotels, and private beaches. One of Dubai's most prestigious addresses with premium prices to match."
    },
    "JLT": {
        "coordinates": [25.0667, 55.1417],
        "neighborhood": "JLT",
        "commute_time": 25,
        "schools_rating": 3,
        "shopping_rating": 3,
        "dining_rating": 4,
        "parks_rating": 3,
        "metro_access": True,
        "beach_access": False,
        "lifestyle": "Mixed",
        "parking_availability": "Adequate",
        "description": "Jumeirah Lakes Towers is a cluster of residential and commercial towers around artificial lakes. More affordable than nearby Dubai Marina while still offering good amenities and metro access."
    },
    "Arabian Ranches": {
        "coordinates": [25.0691, 55.2459],
        "neighborhood": "Arabian Ranches",
        "commute_time": 30,
        "schools_rating": 5,
        "shopping_rating": 3,
        "dining_rating": 3,
        "parks_rating": 5,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Family",
        "parking_availability": "Abundant",
        "description": "A suburban villa community with a golf course, community centers, and good schools. Popular with families looking for more space and a quieter lifestyle away from the city center."
    },
    "Dubai Silicon Oasis": {
        "coordinates": [25.1288, 55.3847],
        "neighborhood": "Dubai Silicon Oasis",
        "commute_time": 35,
        "schools_rating": 3,
        "shopping_rating": 3,
        "dining_rating": 3,
        "parks_rating": 3,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Mixed",
        "parking_availability": "Abundant",
        "description": "A technology park and residential community in the outskirts of Dubai. Offers more affordable housing options with good amenities, especially popular with students and young professionals."
    },
    "International City": {
        "coordinates": [25.1517, 55.4003],
        "neighborhood": "International City",
        "commute_time": 40,
        "schools_rating": 2,
        "shopping_rating": 3,
        "dining_rating": 3,
        "parks_rating": 2,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Budget",
        "parking_availability": "Limited",
        "description": "One of Dubai's most affordable residential areas with themed clusters based on different countries. Popular with budget-conscious residents, but relatively far from central Dubai."
    },
    "Dubai Hills Estate": {
        "coordinates": [25.1227, 55.2711],
        "neighborhood": "Dubai Hills Estate",
        "commute_time": 25,
        "schools_rating": 4,
        "shopping_rating": 4,
        "dining_rating": 3,
        "parks_rating": 5,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Family",
        "parking_availability": "Abundant",
        "description": "A newer master-planned community with villas, townhouses, and apartments surrounding a golf course. Features parks, walking trails, and a large mall, making it popular with families."
    },
    "JVC": {
        "coordinates": [25.0508, 55.2019],
        "neighborhood": "JVC",
        "commute_time": 30,
        "schools_rating": 3,
        "shopping_rating": 3,
        "dining_rating": 3,
        "parks_rating": 3,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Mixed",
        "parking_availability": "Adequate",
        "description": "Jumeirah Village Circle offers a mix of apartments, townhouses, and villas at more reasonable prices than central Dubai. A growing community with increasing amenities and good for small families."
    },
    "Sports City": {
        "coordinates": [25.0334, 55.2277],
        "neighborhood": "Sports City",
        "commute_time": 30,
        "schools_rating": 3,
        "shopping_rating": 2,
        "dining_rating": 2,
        "parks_rating": 4,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Mixed",
        "parking_availability": "Adequate",
        "description": "A residential community built around sports facilities including Dubai International Cricket Stadium. Offers affordable apartments popular with young professionals and sports enthusiasts."
    },
    "Motor City": {
        "coordinates": [25.0484, 55.2370],
        "neighborhood": "Motor City",
        "commute_time": 30,
        "schools_rating": 4,
        "shopping_rating": 3,
        "dining_rating": 3,
        "parks_rating": 4,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Family",
        "parking_availability": "Abundant",
        "description": "A family-friendly community with a racetrack, apartments, townhouses, and villas. Features green spaces and a laid-back atmosphere, with reasonable rental prices compared to central Dubai."
    },
    "DIFC": {
        "coordinates": [25.2117, 55.2762],
        "neighborhood": "DIFC",
        "commute_time": 15,
        "schools_rating": 3,
        "shopping_rating": 4,
        "dining_rating": 5,
        "parks_rating": 2,
        "metro_access": True,
        "beach_access": False,
        "lifestyle": "Professionals",
        "parking_availability": "Adequate",
        "description": "Dubai International Financial Centre is a leading financial hub with luxury apartments, premium office space, and upscale restaurants. Popular with finance professionals who want to live close to work."
    },
    "Deira": {
        "coordinates": [25.2774, 55.3142],
        "neighborhood": "Deira",
        "commute_time": 20,
        "schools_rating": 3,
        "shopping_rating": 4,
        "dining_rating": 4,
        "parks_rating": 2,
        "metro_access": True,
        "beach_access": False,
        "lifestyle": "Mixed",
        "parking_availability": "Limited",
        "description": "One of Dubai's oldest districts with traditional souks, commercial buildings, and residential areas. More affordable than newer areas, with an authentic feel and good public transport links."
    },
    "Bur Dubai": {
        "coordinates": [25.2572, 55.2995],
        "neighborhood": "Bur Dubai",
        "commute_time": 20,
        "schools_rating": 3,
        "shopping_rating": 4,
        "dining_rating": 4,
        "parks_rating": 3,
        "metro_access": True,
        "beach_access": False,
        "lifestyle": "Mixed",
        "parking_availability": "Limited",
        "description": "A historic district on the western side of Dubai Creek with a mix of residential buildings, shops, and cultural sites. More affordable than newer developments with a diverse community."
    },
    "Al Karama": {
        "coordinates": [25.2504, 55.3012],
        "neighborhood": "Al Karama",
        "commute_time": 20,
        "schools_rating": 3,
        "shopping_rating": 4,
        "dining_rating": 4,
        "parks_rating": 2,
        "metro_access": True,
        "beach_access": False,
        "lifestyle": "Mixed",
        "parking_availability": "Limited",
        "description": "A centrally-located residential area known for affordable apartments, shops, and restaurants. Popular with middle-income families and singles due to its central location and reasonable prices."
    },
    "Emirates Hills": {
        "coordinates": [25.0635, 55.1660],
        "neighborhood": "Emirates Hills",
        "commute_time": 25,
        "schools_rating": 5,
        "shopping_rating": 4,
        "dining_rating": 4,
        "parks_rating": 5,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Luxury",
        "parking_availability": "Abundant",
        "description": "An exclusive gated community with luxury villas built around a golf course. One of Dubai's most prestigious addresses, featuring custom-built homes and lush landscaping."
    },
    "Academic City": {
        "coordinates": [25.1205, 55.4181],
        "neighborhood": "Academic City",
        "commute_time": 40,
        "schools_rating": 5,
        "shopping_rating": 2,
        "dining_rating": 2,
        "parks_rating": 3,
        "metro_access": False,
        "beach_access": False,
        "lifestyle": "Students",
        "parking_availability": "Abundant",
        "description": "Home to many universities and colleges, with student accommodation and affordable housing options nearby. Popular with students and academic staff, but located on the outskirts of Dubai."
    }
}
